-- mod by k0n0
-- based on MC's template @ https://forums.civfanatics.com/resources/custom-civilization-modbuddy-template.28386/
-- translated by MeMaus
--------------------------------------------------------------

insert into LocalizedText (Language, Tag, Text)
values  ('zh_CN', 'LOC_CIVILIZATION_K0_MONDSTADT_NAME', '蒙德'),
		('zh_CN', 'LOC_CIVILIZATION_K0_MONDSTADT_DESCRIPTION', '蒙德'),
		('zh_CN', 'LOC_CIVILIZATION_K0_MONDSTADT_ADJECTIVE', '蒙德'),

		('zh_CN', 'LOC_TRAIT_CIVILIZATION_K0_WIND_FREEDOM_NAME',
			'风与自由之都'),
		('zh_CN', 'LOC_TRAIT_CIVILIZATION_K0_WIND_FREEDOM_DESCRIPTION', 
			'所有平原+1 [ICON_Food] 食物和 [ICON_Production] 生产力。'),

		('zh_CN', 'LOC_IMPROVEMENT_MONDSTADT_STATUE_SEVEN_NAME',
			'七天神像-风'),
		('zh_CN', 'LOC_IMPROVEMENT_MONDSTADT_STATUE_SEVEN_DECRIPTION',
			'代替纪念碑. 每回合+3 [ICON_Faith] 信仰, [ICON_Culture] 文化, 和忠诚度。'),

		('zh_CN', 'LOC_UNIT_K0_MONDSTADT_FAVONIUS_KNIGHT_NAME',
			'西风骑士'),
		('zh_CN', 'LOC_UNIT_K0_MONDSTADT_FAVONIUS_KNIGHT_DESCRIPTION',
			'替换剑士，更便宜更强大。'),
		('zh_CN', 'LOC_ABILITY_K0_FAVONIUS_KNIGHT',
			'在平原开启回合时+1 [ICON_Movement] 移动力。'),

-- terrain and shit
		('zh_CN', 'LOC_NAMED_MOUNTAIN_STORMBEARER_MOUNTAINS',
			'望风山地'),
		('zh_CN', 'LOC_NAMED_MOUNTAIN_STORMBEARER_POINT',
			'望风角'),
		('zh_CN', 'LOC_NAMED_MOUNTAIN_STARSNATCH_CLIFF',
			'摘星崖'),
		('zh_CN', 'LOC_NAMED_MOUNTAIN_DRAGONSPINE',
			'龙脊雪山'),
		('zh_CN', 'LOC_NAMED_MOUNTAIN_ENTOMBED_CITY_ANCIENT_PALACE',
			'雪葬之都-旧宫'),
		('zh_CN', 'LOC_NAMED_MOUNTAIN_ENTOMBED_CITY_OUTSKIRTS',
			'雪葬之都-近郊'),
		('zh_CN', 'LOC_NAMED_MOUNTAIN_STARGLOW_CAVERN',
			'星荧洞窟'),
		('zh_CN', 'LOC_NAMED_MOUNTAIN_SKYFROST_NAIL',
			'寒天之钉'),
		('zh_CN', 'LOC_NAMED_MOUNTAIN_BRIGHTCROWN_MOUNTAINS',
			'明冠峡'),

		('zh_CN', 'LOC_NAMED_LAKE_CIDER_LAKE',
			'果酒湖'),
		('zh_CN', 'LOC_NAMED_LAKE_STARFELL_LAKE',
			'星落湖'),

		('zh_CN', 'LOC_NAMED_SEA_FALCON_COAST',
			'鹰翔海滩'),

-- cities and shit
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_1', '蒙德城'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_2', '坠星山谷'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_3', '低语森林'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_4', '千风神殿'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_5', '风起地'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_6', '风啸山坡'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_7', '达达乌帕谷'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_8', '誓言岬'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_9', '覆雪之路'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_10', '眠龙谷'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_11', '苍风高地'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_12', '清泉镇'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_13', '晨曦酒庄'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_14', '奔狼领'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_15', '明冠峡'),
		('zh_CN', 'LOC_CITY_NAME_K0_MONDSTADT_16', '风龙废墟'),

-- citizens
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_1', '杜拉夫'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_2', '蒂迈乌斯'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_3', '斯坦利'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_4', '查尔斯'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_5', '霍夫曼'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_6', '提米'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_7', '劳伦斯'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_8', '斯万'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_9', '瓦格纳'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_10', '舒尔兹'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_11', '阿托斯'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_12', '波托斯'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_13', '伍德'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_14', '薇拉特'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_15', '阿拉米斯'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_16', '奥托'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_MALE_17', '盖伊'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_1', '玛格丽特'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_2', '布兰奇'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_3', '芙罗拉'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_4', '格洛里'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_5', '凯瑟琳'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_6', '玛乔丽'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_7', '莎拉'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_8', '艾拉马斯克'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_9', '维利'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_10', '艾琳'),
		('zh_CN', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_11', '赫塔'),

-- civilopedia and all that crap
		('zh_CN', 'LOC_CIVINFO_K0_MONDSTADT_LOCATION', '果酒湖'),
		('zh_CN', 'LOC_CIVINFO_K0_MONDSTADT_SIZE', '<10 km?'),
		('zh_CN', 'LOC_CIVINFO_K0_MONDSTADT_POPULATION', '>10'),
		('zh_CN', 'LOC_CIVINFO_K0_MONDSTADT_CAPITAL', '蒙德城'),

		('zh_CN',
	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_K0_MONDSTADT_CHAPTER_HISTORY_PARA_1',
	'位于提瓦特东北部的自由的城市。'),
		('zh_CN',
	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_K0_MONDSTADT_CHAPTER_HISTORY_PARA_2',
	'在群山和广阔的平原之间，无忧无虑的微风带着蒲公英的气味——这是风神 巴巴托斯送给我们的礼物——穿过果酒湖，来到了位于湖中央的小岛上的蒙德城。'),
		('zh_CN',
	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_K0_MONDSTADT_CHAPTER_HISTORY_PARA_3',
	'(摘自原神官方网站)');
	