-- mod by k0n0
-- based on MC's template @ https://forums.civfanatics.com/resources/custom-civilization-modbuddy-template.28386/
-- translated by Watermelon!
--------------------------------------------------------------

insert into LocalizedText (Language, Tag, Text)
values  ('es_ES', 'LOC_CIVILIZATION_K0_MONDSTADT_NAME', 'Mondstadt'),
		('es_ES', 'LOC_CIVILIZATION_K0_MONDSTADT_DESCRIPTION', 'Mondstadt'),
		('es_ES', 'LOC_CIVILIZATION_K0_MONDSTADT_ADJECTIVE', 'Mondstadt'),

		('es_ES', 'LOC_TRAIT_CIVILIZATION_K0_WIND_FREEDOM_NAME',
			'Ciudad del viento y la libertad'),
		('es_ES', 'LOC_TRAIT_CIVILIZATION_K0_WIND_FREEDOM_DESCRIPTION', 
			'+1 [ICON_Food] Comida y [ICON_Production] Producción para todos las secciones de llanuras.'),

		('es_ES', 'LOC_IMPROVEMENT_MONDSTADT_STATUE_SEVEN_NAME',
			'Estatua de los Siete: Anemo'),
		('es_ES', 'LOC_IMPROVEMENT_MONDSTADT_STATUE_SEVEN_DECRIPTION',
			'Sustituye Monumento. +3 [ICON_Faith] Fé, [ICON_Culture] Cultura y Lealtad por turno.'),

		('es_ES', 'LOC_UNIT_K0_MONDSTADT_FAVONIUS_KNIGHT_NAME',
			'Caballero de Favonius'),
		('es_ES', 'LOC_UNIT_K0_MONDSTADT_FAVONIUS_KNIGHT_DESCRIPTION',
			'Sustituye a Soldado con espada. Ligeramente más barato y poderoso.'),
		('es_ES', 'LOC_ABILITY_K0_FAVONIUS_KNIGHT',
			'+1 [ICON_Movement] Movimiento cuando está en llanuras.'),

-- terrain and shit
		('es_ES', 'LOC_NAMED_MOUNTAIN_STORMBEARER_MOUNTAINS',
			'Montañas Portatormentas'),
		('es_ES', 'LOC_NAMED_MOUNTAIN_STORMBEARER_POINT',
			'Punto Portatormentas'),
		('es_ES', 'LOC_NAMED_MOUNTAIN_STARSNATCH_CLIFF',
			'Acantilado Estrellado'),
		('es_ES', 'LOC_NAMED_MOUNTAIN_DRAGONSPINE',
			'Espinadragón'),
		('es_ES', 'LOC_NAMED_MOUNTAIN_ENTOMBED_CITY_ANCIENT_PALACE',
			'Ciudad Sepultada - Palacio Antiguo'),
		('es_ES', 'LOC_NAMED_MOUNTAIN_ENTOMBED_CITY_OUTSKIRTS',
			'Ciudad Sepultada - Periferia'),
		('es_ES', 'LOC_NAMED_MOUNTAIN_STARGLOW_CAVERN',
			'Cueva Del Destello Estelar'),
		('es_ES', 'LOC_NAMED_MOUNTAIN_SKYFROST_NAIL',
			'Pilar Del Frío Celestial'),
		('es_ES', 'LOC_NAMED_MOUNTAIN_BRIGHTCROWN_MOUNTAINS',
			'Montaña Coronabrillante'),

		('es_ES', 'LOC_NAMED_LAKE_CIDER_LAKE',
			'Lago de Sidra'),
		('es_ES', 'LOC_NAMED_LAKE_STARFELL_LAKE',
			'Lago Estelar'),

		('es_ES', 'LOC_NAMED_SEA_FALCON_COAST',
			'Costa Del Halcón'),

-- cities and shit
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_1', 'Mondstadt'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_2', 'Valle Estelar'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_3', 'Bosque Susurrante'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_4', 'Templo de Los mil Vientos'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_5', 'Levantamiento'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_6', 'Colina Silbante'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_7', 'Valle Dadaupe'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_8', 'Cabo Del Juramento'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_9', 'Camino Nevado'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_10', 'Valle Dragondurmiente'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_11', 'Meseta de la Ventisca'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_12', 'Aldea Aguaclara'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_13', 'Viñedo del Amanecer'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_14', 'Reino de los Lobos'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_15', 'Cañón Coronabrillante'),
		('es_ES', 'LOC_CITY_NAME_K0_MONDSTADT_16', 'Guarida de Stormterror'),

-- citizens
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_1', 'Draff'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_2', 'Bennett'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_3', 'Kaeya'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_4', 'Charles'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_5', 'Huffman'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_6', 'Timmie'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_7', 'Lawrence'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_8', 'Swan'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_9', 'Wagner'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_10', 'Schulz'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_11', 'Athos'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_12', 'Porthos'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_13', 'Wood'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_14', 'Wyratt'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_15', 'Aramis'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_16', 'Otto'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_MALE_17', 'Guy'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_1', 'Margaret'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_2', 'Fischl'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_3', 'Amber'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_4', 'Glory'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_5', 'Katheryne'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_6', 'Marjorie'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_7', 'Sara'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_8', 'Ella Musk'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_9', 'Vile'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_10', 'Ellin'),
		('es_ES', 'LOC_CITIZEN_K0_MONDSTADT_FEMALE_11', 'Hertha'),

-- civilopedia and all that crap
		('es_ES', 'LOC_CIVINFO_K0_MONDSTADT_LOCATION', 'Lago de Sidra'),
		('es_ES', 'LOC_CIVINFO_K0_MONDSTADT_SIZE', '<10 km�'),
		('es_ES', 'LOC_CIVINFO_K0_MONDSTADT_POPULATION', '>10'),
		('es_ES', 'LOC_CIVINFO_K0_MONDSTADT_CAPITAL', 'Mondstadt'),

		('es_ES',
	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_K0_MONDSTADT_CHAPTER_HISTORY_PARA_1',
	'Una ciudad de libertad que se encuentra al noreste de Teyvat.'),
		('es_ES',
	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_K0_MONDSTADT_CHAPTER_HISTORY_PARA_2',
	'Desde entre montañas y llanuras abiertas, la brisa despreocupada lleva el aroma de los dientes de león. -- un regalo del Dios Anemo, Barbatos -- a través del lago de Sidra hasta Mondstadt, que se encuentra en una isla en medio del lago. '),
		('es_ES',
	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_K0_MONDSTADT_CHAPTER_HISTORY_PARA_3',
	'(Desde el sitio web oficial de Genshin Impact )');
	